# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    - require_trailing_commas
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_returning_null_for_void
    - avoid_void_async
    - cascade_invocations
    - file_names
    - leading_newlines_in_multiline_strings
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - prefer_single_quotes
    - unawaited_futures
    - unnecessary_await_in_return
    - await_only_futures
    - unnecessary_late
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - use_enums
    - avoid_empty_else
    - avoid_dynamic_calls
    - prefer_relative_imports
    - use_colored_box
    - use_decorated_box
    - type_annotate_public_apis
    - no_literal_bool_comparisons
    - directives_ordering
    - avoid_print

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
